// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.239
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Meek.ContentSite.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Partial Content")]
    public partial class PartialContentFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PartialContent.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Partial Content", "In order to maintain my own content\r\nAs a content admin\r\nI want to be able to mai" +
                    "ntain partial page content", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Edit content")]
        [NUnit.Framework.CategoryAttribute("UXSession")]
        public virtual void EditContent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Edit content", new string[] {
                        "UXSession"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I have logged in as a content admin");
#line 9
 testRunner.When("I ask to edit an existing partial content");
#line 10
 testRunner.Then("it should provide me with a populated partial content editor");
#line 11
 testRunner.And("allow me to edit my existing partial content");
#line 12
    testRunner.And("return me to the home page");
#line 13
    testRunner.And("let me navigate to view my partial content");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Viewing content logged in")]
        [NUnit.Framework.CategoryAttribute("UXSession")]
        public virtual void ViewingContentLoggedIn()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Viewing content logged in", new string[] {
                        "UXSession"});
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
 testRunner.Given("I have logged in as a content admin");
#line 18
    testRunner.When("I ask to view an existing page with partial content");
#line 19
    testRunner.Then("It should present me with an edit link");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Viewing content not logged in")]
        [NUnit.Framework.CategoryAttribute("UXSession")]
        public virtual void ViewingContentNotLoggedIn()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Viewing content not logged in", new string[] {
                        "UXSession"});
#line 22
this.ScenarioSetup(scenarioInfo);
#line 23
    testRunner.When("I ask to view an existing page with partial content");
#line 24
    testRunner.Then("It should not present me with an edit link");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Viewing non existent partial content logged in")]
        [NUnit.Framework.CategoryAttribute("UXSession")]
        public virtual void ViewingNonExistentPartialContentLoggedIn()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Viewing non existent partial content logged in", new string[] {
                        "UXSession"});
#line 27
this.ScenarioSetup(scenarioInfo);
#line 28
 testRunner.Given("I have logged in as a content admin");
#line 29
    testRunner.When("I ask for a page with non existent partial content");
#line 30
    testRunner.Then("it should present me with a create content link");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Viewing non existent partial content not logged in")]
        [NUnit.Framework.CategoryAttribute("UXSession")]
        public virtual void ViewingNonExistentPartialContentNotLoggedIn()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Viewing non existent partial content not logged in", new string[] {
                        "UXSession"});
#line 33
this.ScenarioSetup(scenarioInfo);
#line 34
    testRunner.When("I ask for a page with non existent partial content");
#line 35
    testRunner.Then("it should show an empty section");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
